name: Check & fix styling

on:
  push:
    branches-ignore:
      - master
      - main
      - master2

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Setup cache directory
        uses: actions/cache@v3
        with:
          path: .php-cs-fixer.cache
          key: ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-${{ github.sha }}
          restore-keys: ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.php --allow-risky=yes

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
